version: "3.3"
services:
  password-api:
    image: nicopaez/password-api
    expose:
     - "3000"
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - password-api
